### ISSUE TITLE
cannot make it work

### ISSUE THREAD

**Issue by fuzz4** [GrecHouse/lunar_date#1]
hello, I am quite new to HA so forgive me for the stupid  question :
I tried to install , precisely:

- installed the repository on Hacs 
- everything seems correct in custom components
- yaml file added :

- sensor:
  - platform: lunar_date 

still it doesn't find the new entity 

thank you for your help!

**Comment by fuzz4** [comment]
Fixed! After shutting off HA and restarting it worked, thank you for your work!

**Comment by GrecHouse** [comment]
🙏
